### ISSUE TITLE
Search throws error for empty result

### ISSUE THREAD

**Issue by alexsloan** [chartmogul/chartmogul-node#25]
If you search email address, and no results are found, an error is thrown:
```
{ NotFoundError: The requested Resource could not be found. {"code":404,"message":"Can't find any customers with email: \"alex+11223@[domain].com\"","param":"email"}
```

That's pretty unexpected. Would expect to get back an empty search result since this isn't an error, it's just no result.

**Comment by jasonl** [comment]
Hi Alex,

Thanks for letting us know about this, we'll have a look into it. It looks like something we will want change, but we'll need to check it doesn't break any existing integrations.

**Comment by bilbof** [comment]
Possible solution:

https://github.com/chartmogul/chartmogul-node/blob/master/lib/chartmogul/customer.js#L14

```
    return Resource.request(config, 'GET', path, query, callback)
      .catch(err => {
        return JSON.stringify({
          "entries": [],
          "current_page":1,
          "total_pages":null,
          "has_more":false,
          "per_page":200,
          "page":1
        })
      })
```

However, the API is responding with an error code and message. Ideally the API would respond with `{ "entries": [] }` rather than `{"code":404,"message":"Can't find any customers with email: \"nonexistantcustomer@example.com\"","param":"email"}`, but given the current API response I think the client library's response is expected.

I think it would be better to change the behaviour on the API rather than in the client libraries. Thoughts @jasonl @pkopac?

**Comment by bilbof** [comment]
@alexsloan thanks again for reporting this. As with #26 this looks like an error with our Import API. We'll investigate this further and we'll let you know if the error handling behaviour changes in a later version.

Internal ref: DP-538
